#!/bin/csh -f

set dat = `date +"%m%d%y"`
set popcnt = "asmfish-popcnt-$dat"
set bmi2 = "asmfish-bmi2-$dat"
fasmg "x86/fish.asm" "$popcnt" -e 100 -i "VERSION_OS='X'" -i "VERSION_POST = 'popcnt'"
chmod 755 $popcnt
fasmg "x86/fish.asm" "asmfish-bmi2-$dat" -e 100 -i "VERSION_OS='X'" -i "VERSION_POST = 'bmi2'"
chmod 755 $bmi2
zip asmfish-$dat.zip $popcnt $bmi2
