#!/bin/csh -f

### This cshell script builds asmfish on a macOS host for windows, linux android and macOS operating systems.  Simply type "Build" at the command line.  Takes about 5 minutes to run and then zips the binaries into a zip file.
set include=x86\include\
set dat = `date +"%m%d%y"`
set popcnt = "asmfish-popcnt-$dat"
set bmi2 = "asmfish-bmi2-$dat"
set base = "asmfish-base-$dat"
set arm = "armfish-V8-$dat"
set OS1 = "X"   ### macOS
set OS2 = "W"   ### Windows
set OS3 = "L"   ###Linux
set exe = ".exe" ###  suffix used for windows binaries
fasmg "x86/fish.asm" "$base-$OS1" -e 1000 -i "VERSION_OS='X'" -i "VERSION_POST = 'base'"
chmod 755 $base-$OS1
fasmg "x86/fish.asm" "$popcnt-$OS1" -e 1000 -i "VERSION_OS='X'" -i "VERSION_POST = 'popcnt'"
chmod 755 $popcnt-$OS1
fasmg "x86/fish.asm" "$bmi2-$OS1" -e 1000 -i "VERSION_OS='X'" -i "VERSION_POST = 'bmi2'"
chmod 755 $bmi2-$OS1
fasmg "x86\fish.asm" "$base-$OS2$exe" -e 1000 -i "VERSION_OS='W'" -i "PEDANTIC = 1" -i "VERSION_POST = 'base'"
chmod 755 $base-$OS2$exe
fasmg "x86\fish.asm" "$popcnt-$OS2$exe" -e 1000 -i "VERSION_OS='W'" -i "PEDANTIC = 1" -i "VERSION_POST = 'popcnt'"
chmod 755 $popcnt-$OS2$exe
fasmg "x86\fish.asm" "$bmi2-$OS2$exe" -e 1000 -i "VERSION_OS='W'" -i "PEDANTIC = 1" -i "VERSION_POST = 'bmi2'"
chmod 755 $bmi2-$OS2$exe
fasmg "x86\fish.asm" "$base-$OS3" -e 1000 -i "VERSION_OS='L'" -i "PEDANTIC = 1" -i "VERSION_POST = 'base'"
chmod 755 $base-$OS3
fasmg "x86\fish.asm" "$popcnt-$OS3" -e 1000 -i "VERSION_OS='L'" -i "PEDANTIC = 1" -i "VERSION_POST = 'popcnt'"
chmod 755 $popcnt-$OS3
fasmg "x86\fish.asm" "$bmi2-$OS3" -e 1000 -i "VERSION_OS='L'" -i "PEDANTIC = 1" -i "VERSION_POST = 'bmi2'"
chmod 755 $bmi2-$OS3
fasmg "arm\fish.arm" "$arm-$OS3" -e 1000 -i "VERSION_OS='L'" -i "PEDANTIC = 1" -i "VERSION_POST = 'v8'"
chmod 755 $arm-$OS3
zip asmfish-$dat-mf.zip $base-$OS1 $popcnt-$OS1 $bmi2-$OS1 $base-$OS2$exe $popcnt-$OS2$exe $bmi2-$OS2$exe $base-$OS3 $popcnt-$OS3 $bmi2-$OS3 $arm-$OS3
